name: Release Automática
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🗂 Garantir que a pasta artifacts existe
        run: mkdir -p artifacts

      - name: 📦 Copiar arquivos importantes para artifacts
        run: |
          cp -r resources artifacts/
          cp server.cfg artifacts/
          cp env.example.cfg artifacts/
          cp database.sql artifacts/

      - name: 📦 Compactar artifacts
        run: zip -r artifacts.zip artifacts/*

      - name: 🚀 Criar Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.run_number }}"
          name: "Release v${{ github.run_number }}"
          files: artifacts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
